// Every US state, DC, and Canadian province and territory, as in the boundary file.
// Generated from public/geo/north-america.topo.json; a test checks they match.

const CODES = [
  'CA-AB',
  'CA-BC',
  'CA-MB',
  'CA-NB',
  'CA-NL',
  'CA-NS',
  'CA-NT',
  'CA-NU',
  'CA-ON',
  'CA-PE',
  'CA-QC',
  'CA-SK',
  'CA-YT',
  'US-AK',
  'US-AL',
  'US-AR',
  'US-AZ',
  'US-CA',
  'US-CO',
  'US-CT',
  'US-DC',
  'US-DE',
  'US-FL',
  'US-GA',
  'US-HI',
  'US-IA',
  'US-ID',
  'US-IL',
  'US-IN',
  'US-KS',
  'US-KY',
  'US-LA',
  'US-MA',
  'US-MD',
  'US-ME',
  'US-MI',
  'US-MN',
  'US-MO',
  'US-MS',
  'US-MT',
  'US-NC',
  'US-ND',
  'US-NE',
  'US-NH',
  'US-NJ',
  'US-NM',
  'US-NV',
  'US-NY',
  'US-OH',
  'US-OK',
  'US-OR',
  'US-PA',
  'US-RI',
  'US-SC',
  'US-SD',
  'US-TN',
  'US-TX',
  'US-UT',
  'US-VA',
  'US-VT',
  'US-WA',
  'US-WI',
  'US-WV',
  'US-WY',
] as const;

/** English names, for spreadsheets that spell the state or province out. */
const NAMES: Record<(typeof CODES)[number], string> = {
  'CA-AB': 'Alberta',
  'CA-BC': 'British Columbia',
  'CA-MB': 'Manitoba',
  'CA-NB': 'New Brunswick',
  'CA-NL': 'Newfoundland and Labrador',
  'CA-NS': 'Nova Scotia',
  'CA-NT': 'Northwest Territories',
  'CA-NU': 'Nunavut',
  'CA-ON': 'Ontario',
  'CA-PE': 'Prince Edward Island',
  'CA-QC': 'Quebec',
  'CA-SK': 'Saskatchewan',
  'CA-YT': 'Yukon',
  'US-AK': 'Alaska',
  'US-AL': 'Alabama',
  'US-AR': 'Arkansas',
  'US-AZ': 'Arizona',
  'US-CA': 'California',
  'US-CO': 'Colorado',
  'US-CT': 'Connecticut',
  'US-DC': 'District of Columbia',
  'US-DE': 'Delaware',
  'US-FL': 'Florida',
  'US-GA': 'Georgia',
  'US-HI': 'Hawaii',
  'US-IA': 'Iowa',
  'US-ID': 'Idaho',
  'US-IL': 'Illinois',
  'US-IN': 'Indiana',
  'US-KS': 'Kansas',
  'US-KY': 'Kentucky',
  'US-LA': 'Louisiana',
  'US-MA': 'Massachusetts',
  'US-MD': 'Maryland',
  'US-ME': 'Maine',
  'US-MI': 'Michigan',
  'US-MN': 'Minnesota',
  'US-MO': 'Missouri',
  'US-MS': 'Mississippi',
  'US-MT': 'Montana',
  'US-NC': 'North Carolina',
  'US-ND': 'North Dakota',
  'US-NE': 'Nebraska',
  'US-NH': 'New Hampshire',
  'US-NJ': 'New Jersey',
  'US-NM': 'New Mexico',
  'US-NV': 'Nevada',
  'US-NY': 'New York',
  'US-OH': 'Ohio',
  'US-OK': 'Oklahoma',
  'US-OR': 'Oregon',
  'US-PA': 'Pennsylvania',
  'US-RI': 'Rhode Island',
  'US-SC': 'South Carolina',
  'US-SD': 'South Dakota',
  'US-TN': 'Tennessee',
  'US-TX': 'Texas',
  'US-UT': 'Utah',
  'US-VA': 'Virginia',
  'US-VT': 'Vermont',
  'US-WA': 'Washington',
  'US-WI': 'Wisconsin',
  'US-WV': 'West Virginia',
  'US-WY': 'Wyoming',
};

export const REGION_CODES = {
  all: new Set<string>(CODES),
  /** Two-letter postal codes; no US code collides with a Canadian one. */
  byPostal: new Map<string, string>(CODES.map((c) => [c.slice(3), c])),
  /** Lowercase names, plus "québec", "newfoundland", and "washington dc". */
  byName: new Map<string, string>([
    ...CODES.map((c) => [NAMES[c].toLowerCase(), c] as [string, string]),
    ['québec', 'CA-QC'],
    ['newfoundland', 'CA-NL'],
    ['washington dc', 'US-DC'],
    ['washington, dc', 'US-DC'],
    ['washington d.c.', 'US-DC'],
    ['yukon territory', 'CA-YT'],
  ]),
};
