// Every US state, DC, and Canadian province and territory, as in the boundary file.
// Generated from public/geo/north-america.topo.json; a test checks they match.

const CODES = [
  'CA-AB',
  'CA-BC',
  'CA-MB',
  'CA-NB',
  'CA-NL',
  'CA-NS',
  'CA-NT',
  'CA-NU',
  'CA-ON',
  'CA-PE',
  'CA-QC',
  'CA-SK',
  'CA-YT',
  'US-AK',
  'US-AL',
  'US-AR',
  'US-AZ',
  'US-CA',
  'US-CO',
  'US-CT',
  'US-DC',
  'US-DE',
  'US-FL',
  'US-GA',
  'US-HI',
  'US-IA',
  'US-ID',
  'US-IL',
  'US-IN',
  'US-KS',
  'US-KY',
  'US-LA',
  'US-MA',
  'US-MD',
  'US-ME',
  'US-MI',
  'US-MN',
  'US-MO',
  'US-MS',
  'US-MT',
  'US-NC',
  'US-ND',
  'US-NE',
  'US-NH',
  'US-NJ',
  'US-NM',
  'US-NV',
  'US-NY',
  'US-OH',
  'US-OK',
  'US-OR',
  'US-PA',
  'US-RI',
  'US-SC',
  'US-SD',
  'US-TN',
  'US-TX',
  'US-UT',
  'US-VA',
  'US-VT',
  'US-WA',
  'US-WI',
  'US-WV',
  'US-WY',
] as const;

export const REGION_CODES = {
  all: new Set<string>(CODES),
  /** Two-letter postal codes; no US code collides with a Canadian one. */
  byPostal: new Map<string, string>(CODES.map((c) => [c.slice(3), c])),
};
